# Imports: standard library
from typing import Any, Dict, List

BEDMASTER_PREFIX = "bedmaster"
BEDMASTER_EXT = ".mat"

MATFILE_EXPECTED_GROUPS: List[str] = [
    "vs",
    "vs_time_corrected",
    "vs_packet",
    "vs_seq",
    "vs_time_corrected",
    "vs_time_original",
    "wv",
    "wv_time_corrected",
    "wv_time_original",
]

MAPPING_DEPARTMENTS: Dict[str, List[Any]] = {
    # EDW dept name: [possible file name]
    "MGH BIGELOW 6 PICU": ["BIG06"],
    "MGH BIGELOW 7": ["BIG7"],
    "MGH BIGELOW 9 MED": ["BIG09", "BIG9"],
    "MGH IP PULM GRYBIG9": ["BIG09PU"],
    "MGH PULM LAB BIG9": ["BIG09PU"],
    "MGH DLYSIS HEMO BIG10": ["BIG10"],
    "MGH BIGELOW 11 MED": ["BIG11"],
    "MGH BIGELOW 12": ["BIG12"],
    "MGH BIGELOW 13 RACU": ["BIG13"],
    "MGH BIGELOW 14 MED": ["BIG14"],
    "MGH BLAKE 4 ENDO DEPT": [None],
    "MGH BLAKE 6 TRANSPLANT": ["BLAKE6"],
    "MGH BLAKE 7 MICU": ["BLK07", "MICU"],
    "MGH BLAKE 8 CARD SICU": ["BLK08"],
    "MGH BLAKE 10 NICU": ["BLK10", "NICU"],
    "MGH BLAKE 10 LII NURS": ["BLK10"],
    "MGH BLAKE 11 PSYCH": [None],
    "MGH BLAKE 12 ICU": ["BLK12"],
    "MGH BLAKE 13 OB": ["BLK13"],
    "MGH BLAKE 13N NURSERY": ["BLK13"],
    "MGH BLAKE 13I NURSERY": ["BLK13"],
    "MGH BLAKE 14 L&D": ["BLK14"],
    "MGH BLAKE 14 NURSERY": ["BLK14"],
    "MGH ELLISON 3 ICU": [None],
    "MGH ELLISON 3 PACU": ["PACUE"],
    "MGH ELLISON 4 SICU": ["ELL04", "ELL4"],
    "MGH ELLISON 6 ORTH\\URO": ["ELL6"],
    "MGH ELLISON 7 SURG\\URO": ["ELL-7"],
    "MGH ELLISON 8 CARDSURG": ["ELL08", "ELL8"],
    "MGH ELLISON 9 MED\\CCU": ["ELL09", "ELL9"],
    "MGH ELLISON 10 STP DWN": ["ELL10"],
    "MGH ELLISON11 CARD\\INT": ["ELL11"],
    "MGH ELLISON 12 MED": ["ELL12"],
    "MGH ELLISON13A OB-ANTE": ["ELL13"],
    "MGH ELLISON13I NRSRY": ["EL13NL1"],
    "MGH ELLISON13N NRSRY": ["EL13NL2"],
    "MGH ELLISON13O OB-POST": ["EL13SCN"],
    "MGH ELLISON 14 BRN ICU": ["ELL14"],
    "MGH ELLISON 14 PLASTCS": ["ELL14"],
    "MGH ELLISON 16 MED ONC": ["ELL16"],
    "MGH ELLISON 17 PEDI": ["ELL17"],
    "MGH ELLISON 18 PEDI": ["ELL18"],
    "MGH ELLISON19 THOR/VAS": ["ELL19"],
    "MGH LUNDER 6 NEURO ICU": ["LUN06"],
    "MGH IMG CT MG LND6": ["LUN06IM"],
    "MGH IMG MR MG LND6": ["LUN06IM"],
    "MGH IMG PETCT MG LND6": ["LUN06IM"],
    "MGH LUNDER 7 NEURO": ["LUN07"],
    "MGH LUNDER 8 NEURO": ["LUN08"],
    "MGH LUNDER 9 ONCOLOGY": ["LUN09"],
    "MGH LUNDER 10 ONCOLOGY": ["LUN10"],
    "MGH WHITE 3 PACU": [None],
    "MGH WHITE 6 ORTHO\\OMF": ["WHT06"],
    "MGH WHITE 7 GEN SURG": ["WHT07"],
    "MGH WHITE 8 MEDICINE": ["WHT08", "WHITE8"],
    "MGH WHITE 9 MEDICINE": ["WHT09", "WHITE9"],
    "MGH WHITE 10 MEDICINE": ["WHITE10"],
    "MGH WHITE 11 MEDICINE": ["WHITE11"],
    "MGH WHITE 12": ["WHT12"],
    "MGH WHITE 13 PACU": ["WHT13"],
    "MGH EMERGENCY": ["EDACUTE", "EDCDU", "EDPEDI", "EDURGENT"],
    "MGH CARDIAC CATH LAB": [None],
    "MGH PERIOPERATIVE DEPT": [None],
    "MGH EP PACER LAB": [None],
    "MGH CPC": [None],
    "MGH PHILLIPS 20 MED": [None],
    "MGH PHILLIPS 22 GYN/SG": ["PH22"],
    "MGH WANG 3 ICU": ["WANG3"],
    "MGH WANG 3 CPC": ["PACUW"],
    "MGH CC INFUSION YAW8": ["YAW08"],
    "MGH PROCEDURE RM PICU": ["ELL02PR"],
    "MGH PROTON THERAPY": ["NPTC"],
    # "ELL02": ["ELL02"],
    # "ELL20": ["ELL20"],
    # "ELL21": ["ELL21"],
    # "GRB02": ["GRB02"],
    # "BLK09": ["BLK09"],
    # "BLK260": ["BLK260"],
    # "CAU": ["CAU"],
    # "PICU": ["PICU"],
    # "YAW10": ["YAW10"],
}

ALARMS_FILES: Dict[str, Any] = {
    "columns": [
        "UnitBedUID",
        "AlarmStartTime",
        "AlarmLevel",
        "AlarmMessage",
        "AlarmDuration",
        "PatientID",
        "Bed",
        "Unit",
    ],
    "names": MAPPING_DEPARTMENTS,
    "source": "alarms",
}

# fmt: off
ICU_SCALE_UNITS = {
    "I":         {"scaling_factor": 0.0243, "units": "mV"},
    "II":        {"scaling_factor": 0.0243, "units": "mV"},
    "III":       {"scaling_factor": 0.0243, "units": "mV"},
    "V":         {"scaling_factor": 0.0243, "units": "mV"},
    "SPO2":      {"scaling_factor": 0.039,  "units": "%"},
    "RR":        {"scaling_factor": 0.078,  "units": "ohms"},
    "CO2":       {"scaling_factor": 0.25,   "units": "mmHg"},
    "AVR":       {"scaling_factor": 0.0243, "units": "mV"},
    "AVF":       {"scaling_factor": 0.0243, "units": "mV"},
    "AVL":       {"scaling_factor": 0.0243, "units": "mV"},
    "ART1":      {"scaling_factor": 0.2,    "units": "mmHg"},
    "ART6":      {"scaling_factor": 0.2,    "units": "mmHg"},
    "FEM4":      {"scaling_factor": 0.2,    "units": "mmHg"},
    "PA2":       {"scaling_factor": 0.2,    "units": "mmHg"},
    "CVP3":      {"scaling_factor": 0.2,    "units": "mmHg"},
    "CUFF":      {"scaling_factor": 1,      "units": "mmHg"},
    "HR":        {"scaling_factor": 1,      "units": "Bpm"},
    "PVC":       {"scaling_factor": 1,      "units": "Bpm"},
    "ART1S":     {"scaling_factor": 1,      "units": "mmHg"},
    "ART1D":     {"scaling_factor": 1,      "units": "mmHg"},
    "ART1M":     {"scaling_factor": 1,      "units": "mmHg"},
    "ART1R":     {"scaling_factor": 1,      "units": "mmHg"},
    "ART6S":     {"scaling_factor": 1,      "units": "mmHg"},
    "ART6D":     {"scaling_factor": 1,      "units": "mmHg"},
    "ART6M":     {"scaling_factor": 1,      "units": "mmHg"},
    "ART6R":     {"scaling_factor": 1,      "units": "mmHg"},
    "FEM4S":     {"scaling_factor": 1,      "units": "mmHg"},
    "FEM4D":     {"scaling_factor": 1,      "units": "mmHg"},
    "FEM4M":     {"scaling_factor": 1,      "units": "mmHg"},
    "FEM4R":     {"scaling_factor": 1,      "units": "mmHg"},
    "ASBRAMP":   {"scaling_factor": 0.1,    "units": "sec"},
    "BT":        {"scaling_factor": 0.1,    "units": "Celcius"},
    "IT":        {"scaling_factor": 0.1,    "units": "Celcius"},
    "CO":        {"scaling_factor": 0.1,    "units": "L/min"},
    "CO2RR":     {"scaling_factor": 1,      "units": "BrMin"},
    "DYNRES":    {"scaling_factor": 0.1,    "units": "cmH2O/L/sec"},
    "FLWR":      {"scaling_factor": 1,      "units": "L/min"},
    "FLWTRIG":   {"scaling_factor": 1,      "units": "L/min"},
    "I:E":       {"scaling_factor": 1,      "units": "Ratio"},
    "INSPMEAS":  {"scaling_factor": 0.01,   "units": "sec"},
    "INSPTM":    {"scaling_factor": 0.01,   "units": "sec"},
    "IN_HLD":    {"scaling_factor": 0.1,    "units": "sec"},
    "MAWP":      {"scaling_factor": 1,      "units": "cmH2O"},
    "MV":        {"scaling_factor": 0.1,    "units": "L/min"},
    "PA2D":      {"scaling_factor": 1,      "units": "mmHg"},
    "PA2M":      {"scaling_factor": 1,      "units": "mmHg"},
    "PA2S":      {"scaling_factor": 1,      "units": "mmHg"},
    "PEEP":      {"scaling_factor": 1,      "units": "cmH2O"},
    "PIP":       {"scaling_factor": 1,      "units": "cmH2O"},
    "PPLAT":     {"scaling_factor": 1,      "units": "cmH2O"},
    "PRSSUP":    {"scaling_factor": 1,      "units": "cmH2O"},
    "PTRR":      {"scaling_factor": 1,      "units": "BrMin"},
    "RESP":      {"scaling_factor": 1,      "units": "BrMin"},
    "SENS":      {"scaling_factor": 0.1,    "units": "cmH20"},
    "SETFIO2":   {"scaling_factor": 1,      "units": "%"},
    "SETIE":     {"scaling_factor": 1,      "units": "ratio"},
    "SETPCP":    {"scaling_factor": 1,      "units": "cmH2O"},
    "SETTV":     {"scaling_factor": 1,      "units": "ml"},
    "SPO2%":     {"scaling_factor": 1,      "units": "%"},
    "SPO2R":     {"scaling_factor": 1,      "units": "Bpm"},
    "SPONTMV":   {"scaling_factor": 0.1,    "units": "L/min"},
    "STATRES":   {"scaling_factor": 0.1,    "units": "cmH20/L/Sec"},
    "TV":        {"scaling_factor": 1,      "units": "ml"},
    "Vent Rate": {"scaling_factor": 1,      "units": "BrMin"},
    "NBPM":      {"scaling_factor": 1,      "units": "mmHg"},
    "NBPS":      {"scaling_factor": 1,      "units": "mmHg"},
    "NBPD":      {"scaling_factor": 1,      "units": "mmHg"},
    "TMP1":      {"scaling_factor": 0.1,    "units": "Celcius"},
    "TMP2":      {"scaling_factor": 0.1,    "units": "Celcius"},
}
# fmt: on
