# Imports: standard library
from typing import Any, Dict

# Imports: first party
from ml4c3.definitions.icu import EDW_FILES, BM_SOURCES, ALARMS_FILES

# fmt: off
SOURCES = [
    BM_SOURCES["waveform"][3:],                             # 0
    BM_SOURCES["vitals"][3:],                               # 1
    BM_SOURCES["ecg_features"][3:],                         # 2
    ALARMS_FILES["source"][3:],                             # 3
    EDW_FILES["events_file"]["source"][4:],                 # 4
    EDW_FILES["med_file"]["source"][4:],                    # 5
    EDW_FILES["surgery_file"]["source"][4:],                # 6
    EDW_FILES["other_procedures_file"]["source"][4:],       # 7
    EDW_FILES["transfusions_file"]["source"][4:],           # 8
    EDW_FILES["lab_file"]["source"][4:],                    # 9
    EDW_FILES["vitals_file"]["source"][4:],                 # 10
    EDW_FILES["demo_file"]["source"][4:],                   # 11
]
# fmt: on

DEFINED_TMAPS: Dict[str, Any] = {
    SOURCES[0]: [
        "i",
        "ii",
        "iii",
        "v",
        "spo2",
        "pa2",
        "art1",
        "bis",
        "co2",
        "cvp3",
        "fem4",
        "rr",
    ],
    SOURCES[1]: [
        "art1d",
        "art1m",
        "art1r",
        "art1s",
        "asbramp",
        "bis",
        "bt",
        "co",
        "co2rr",
        "cuff",
        "cvp3",
        "dynres",
        "emg",
        "fem4d",
        "fem4m",
        "fem4r",
        "fem4s",
        "flwr",
        "flwtrig",
        "hr",
        "i:e",
        "in_hld",
        "inspmeas",
        "insptm",
        "it",
        "mawp",
        "mv",
        "nbpd",
        "nbpm",
        "nbps",
        "pa2d",
        "pa2m",
        "pa2s",
        "peep",
        "pip",
        "pplat",
        "prssup",
        "ptrr",
        "pvc",
        "resp",
        "sens",
        "setfio2",
        "setie",
        "setpcp",
        "settv",
        "spo2%",
        "spo2r",
        "spontmv",
        "sqi",
        "sr",
        "statres",
        "tv",
        "vent rate",
    ],
    SOURCES[2]: [
        "r_peaks",
        "p_peaks",
        "q_peaks",
        "s_peaks",
        "t_peaks",
        "r_onsets",
        "r_offsets",
        "p_onsets",
        "p_offsets",
        "t_onsets",
        "t_offsets",
        "pr_interval",
        "pr_segment",
        "qt_interval",
        "st_segment",
        "tp_segment",
        "rr_interval",
        "qrs_interval",
        "st_height",
        "qrs_amplitude",
    ],
    SOURCES[3]: ["cpp_low", "v_tach", "apnea"],
    SOURCES[4]: ["code_start", "rapid_response_start"],
    SOURCES[5]: [
        "aspirin_325_mg_tablet",
        "cefazolin_2_gram|50_ml_in_dextrose_(iso-osmotic)_intravenous_piggyback",
        "lactated_ringers_iv_bolus",
        "norepinephrine_infusion_syringe_in_swfi_80_mcg|ml_cmpd_central_mgh",
        "sodium_chloride_0.9_%_intravenous_solution",
    ],
    SOURCES[6]: ["colonoscopy", "coronary_artery_bypass_graft"],
    SOURCES[7]: ["hemodialysis", "hemodialysis_|_ultrafiltration"],
    SOURCES[8]: [
        "transfuse_red_blood_cells",
        "transfuse_platelets",
        "transfuse_cryoprecipitate",
        "transfuse_fresh_frozen_plasma",
        "massive_transfusion_protocol",
    ],
    SOURCES[9]: [
        "creatinine",
        "magnesium",
        "potassium",
        "calcium",
        "sodium",
        "chloride",
        "glucose",
        "phosphorus",
        "bilirubin_(direct)",
        "bilirubin_(total)",
        "wbc",
        "troponin_t-hs_gen5",
        "hct",
        "hgb",
        "rbc",
        "bun",
        "ast",
        "base_excess,_unspecified",
        "hco3,_unspecified",
        "fio2",
        "ph,_arterial",
        "ph,_unspecified",
        "pco2,_arterial",
        "pco2,_unspecified",
        "pco2_(uncorrected)",
        "so2,_unspecified",
        "lactic_acid-poc",
        "ptt",
        "o2_sat_(so2,_arterial)",
        "alk_phos",
        "plt",
        "anion_gap",
        "total_protein",
        "albumin",
        "platelets",
    ],
    SOURCES[10]: [
        "pulse",
        "r_phs_ob_bp_systolic_outgoing",
        "blood_pressure",
        "r_heart_rate_source",
        "r_saturated_venous_o2",
        "r_map",
        "r_cpn_glasgow_coma_scale_score",
        "temperature",
        "respirations",
        "urine_output",
    ],
    f"{SOURCES[11]}_language": [
        "admin_type",
        "admin_diag",
        "race",
        "end_stay_type",
        "tobacco_hist",
        "alcohol_hist",
    ],
    f"{SOURCES[11]}_continuous": [
        "department_id",
        "department_nm",
        "room_bed",
        "move_time",
        "local_time",
        "medical_hist",
        "surgical_hist",
    ],
    f"{SOURCES[11]}_event": ["admin_date", "birth_date", "end_date"],
    f"{SOURCES[11]}_categorical": {"sex": {"male": 0, "female": 1}},
    "other": ["visits", "length_of_stay", "weight", "height"],
    "bm_signals": SOURCES[:4],
    "edw_signals": SOURCES[4:],
}
